force-app/main/default/objects/Division_Manager__c/Division_Manager__c.object-meta.xml
<CustomObject>
    <label>Division Manager</label>
    <nameField>
        <label>Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Division Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Division_Manager__c/fields/Avatar__c.field-meta.xml
<CustomField>
    <fullName>Avatar__c</fullName>
    <label>Avatar</label>
    <length>48</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Division_Manager__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Division_Manager__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>48</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Division_Manager__c/fields/Stats_Data__c.field-meta.xml
<CustomField>
    <fullName>Stats_Data__c</fullName>
    <label>Stats Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Division_Manager__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Division_Manager__c/fields/Tags__c.field-meta.xml
<CustomField>
    <fullName>Tags__c</fullName>
    <label>Tags</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesData.cls
/**
 * Created 23.01.2020.
 */

public with sharing class SalesData {

    @RemoteAction
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getRecords() {
        
        // fetching the Records via SOQL
        List<Division_Manager__c> Records = new List<Division_Manager__c>();
        Records = [SELECT Id, Name, Color__c, Avatar__c, Country__c, Status__c, Tags__c, Stats_Data__c FROM Division_Manager__c];

        Map<String, Object> result = new Map<String, Object>{
            'records' => Records
        };
        return result;
   }
}